"""Generate ``_app/config/perception.yaml`` from the project PerceptionSpec.

One entry per detector; the ``_app`` launch runs one ``trainit_perception``
``detector_node`` per PURE-PYTHON entry (external-node methods publish the same
contract from their own node). ``params`` is the tuned dict VERBATIM — the live
tuner and this file serialize the same thing, which is the "TSA generates what you
tuned" guarantee.

Loaded with ``yaml.safe_load`` by ``detector_node`` (a plain config file, not ROS 2
parameters), so typing is python-level; floats are still emitted as floats for
readability and to match the runtime profile documentation.
"""

from __future__ import annotations

import yaml

from ..model import CanonicalProject

_HEADER = (
    '# Generated by the TrainIt Setup Assistant from the project PerceptionSpec\n'
    '# (the Perception step). One entry per detector; the _app launch runs one\n'
    '# trainit_perception detector_node per pure-python entry. The tree\'s\n'
    '# DetectObject consumes /perception/<name>/detections.\n'
)

_DEFAULT_INPUT = {
    'rgb': '/camera/color/image_raw',
    'depth': '/camera/depth/image_rect_raw',
    'camera_info': '/camera/color/camera_info',
}


def build_perception_yaml(project: CanonicalProject) -> str:
    per = project.perception
    cam = per.camera if per else None
    detectors = {}
    for d in (per.detectors if per else []):
        detectors[d.name] = {
            'method': d.method.value,
            'input': {
                'rgb': d.rgb_topic or (cam.rgb_topic if cam else _DEFAULT_INPUT['rgb']),
                'depth': d.depth_topic or (cam.depth_topic if cam
                                           else _DEFAULT_INPUT['depth']),
                'camera_info': d.camera_info_topic or (
                    cam.camera_info_topic if cam else _DEFAULT_INPUT['camera_info']),
            },
            'params': dict(d.params),
            'continuous': bool(d.continuous),
            'rate_hz': float(d.rate_hz),
        }
    body = yaml.safe_dump({'detectors': detectors}, sort_keys=False,
                          default_flow_style=None)
    return _HEADER + body
