"""Generate the ``scene_manager_node`` ``scene.yaml`` from the project SceneSpec.

Mirrors ``big1500_isaac/scripts/scene_from_usd.py`` but sourced from the
``CanonicalProject``: static/actuated objects become CHECKED collision meshes/prims
the robot must avoid; dynamic objects are collision-ALLOWED; grasp targets become
``attach_object_ids`` (they attach to the tool on gripper close). Loaded by
``trainit_motion_runtime/scene_manager_node`` into the MoveIt planning scene (mock,
isaac, real) so what the assistant configures against == what the bundle runs.
"""

from __future__ import annotations

from ..model import CanonicalProject
from ..model.enums import ShapeType


def _num(v) -> str:
    # ALWAYS a float literal (0.0, 1.0, 0.5813) — scene_manager_node declares position/
    # orientation/scale/force_republish_hz as DOUBLE; emitting an int (0) would make ROS2
    # type the param as integer -> a type mismatch that can break scene loading.
    return repr(round(float(v), 6))


def _nums(vals) -> str:
    return '[' + ', '.join(_num(v) for v in vals) + ']'


def _strs(vals) -> str:
    return '[' + ', '.join(str(v) for v in vals) + ']'


def build_scene_yaml(project: CanonicalProject) -> str:
    scene = project.scene
    frame = project.robot.base_frame
    objs = scene.objects
    out = [
        '# Generated by the TrainIt Setup Assistant from the project SceneSpec.',
        '# Loaded by trainit_motion_runtime/scene_manager_node into the MoveIt planning',
        '# scene (mock | isaac | real). static/actuated = CHECKED collision; dynamic =',
        '# collision-allowed; grasp targets attach to the tool on gripper close.',
        'scene_manager_node:',
        '  ros__parameters:',
        f'    frame_id: {frame}',
        f'    force_republish_hz: {_num(scene.force_republish_hz)}',
        '    scene_update_wait_ms: 800',
        f'    gripper_cmd_topic: "{scene.gripper_cmd_topic}"',
        f'    scene_reset_topic: "{scene.scene_reset_topic}"',
        f'    attach_link: {scene.attach_link}',
        f'    attached_collision_check: {"true" if scene.attached_collision_check else "false"}',
        f'    grasp_attach_mode: {scene.grasp_attach_mode}',
    ]
    # NEVER emit an empty sequence or an empty mapping: YAML gives them no type, so the
    # ROS 2 parameter parser reports "No parameter value set" and scene_manager_node
    # ABORTS at construction (SIGABRT, before it can log anything). Omitting the key
    # instead lets the node's own declared default apply — it declares every one of these
    # with an empty default, so the behaviour is identical and it actually starts.
    _lists = (('touch_links', list(scene.touch_links)),
              ('attach_object_ids', list(scene.grasp_target_ids())),
              ('object_ids', [o.id for o in objs]))
    for key, vals in _lists:
        if vals:
            out.append(f'    {key}: {_strs(vals)}')
    if objs:
        out.append('    objects:')
    for o in objs:
        out.append(f'      {o.id}:')
        if o.is_mesh():
            out.append('        type: mesh')
            out.append(f'        mesh_path: "{o.mesh_resource or ""}"')
            out.append(f'        scale: {_nums(o.scale)}')
        elif o.shape is ShapeType.SPHERE:
            out.append('        type: sphere')
            out.append(f'        radius: {_num(o.dims[0])}')
        elif o.shape is ShapeType.CYLINDER:
            out.append('        type: cylinder')
            out.append(f'        radius: {_num(o.dims[0])}')
            out.append(f'        height: {_num(o.dims[1])}')
        else:  # box (cone/others fall back to their AABB box)
            out.append('        type: box')
            out.append(f'        size: {_nums(o.aabb_dims())}')
        out.append(f'        position: {_nums(o.position)}')
        out.append(f'        orientation: {_nums(o.orientation)}')
        out.append(f'        dynamic: {"true" if o.is_dynamic() else "false"}')
        # AABB bounding box (extents + local centre offset) used when this grasp target
        # attaches to the tool as a cheap box (grasp_attach_mode: attach_box).
        if o.is_grasp_target() and o.is_mesh() and len(o.dims) == 3:
            out.append(f'        grasp_box: {_nums(o.dims)}')
            out.append(f'        grasp_box_center: {_nums(o.aabb_center)}')
        # metadata for the future touchable-ACM refinement (scene_manager_node may
        # leave these attached<->static pairs allowed even when the check is ON).
        if o.touchable_collision_ids:
            out.append(f'        touchable_collision_ids: {_strs(o.touchable_collision_ids)}')
    return '\n'.join(out) + '\n'
