"""Generate the ``scene_manager_node`` ``scene.yaml`` from the project SceneSpec.

Mirrors ``big1500_isaac/scripts/scene_from_usd.py`` but sourced from the
``CanonicalProject``: static/actuated objects become CHECKED collision meshes/prims
the robot must avoid; dynamic objects are collision-ALLOWED; grasp targets become
``attach_object_ids`` (they attach to the tool on gripper close). Loaded by
``trainit_motion_runtime/scene_manager_node`` into the MoveIt planning scene (mock,
isaac, real) so what the assistant configures against == what the bundle runs.
"""

from __future__ import annotations

from ..model import CanonicalProject
from ..model.enums import ShapeType


def _num(v) -> str:
    f = float(v)
    return str(int(f)) if f == int(f) else repr(round(f, 6))


def _nums(vals) -> str:
    return '[' + ', '.join(_num(v) for v in vals) + ']'


def _strs(vals) -> str:
    return '[' + ', '.join(str(v) for v in vals) + ']'


def build_scene_yaml(project: CanonicalProject) -> str:
    scene = project.scene
    frame = project.robot.base_frame
    objs = scene.objects
    out = [
        '# Generated by the TrainIt Setup Assistant from the project SceneSpec.',
        '# Loaded by trainit_motion_runtime/scene_manager_node into the MoveIt planning',
        '# scene (mock | isaac | real). static/actuated = CHECKED collision; dynamic =',
        '# collision-allowed; grasp targets attach to the tool on gripper close.',
        'scene_manager_node:',
        '  ros__parameters:',
        f'    frame_id: {frame}',
        f'    force_republish_hz: {_num(scene.force_republish_hz)}',
        '    scene_update_wait_ms: 800',
        f'    gripper_cmd_topic: {scene.gripper_cmd_topic}',
        f'    attach_link: {scene.attach_link}',
        f'    touch_links: {_strs(scene.touch_links)}',
        f'    attached_collision_check: {"true" if scene.attached_collision_check else "false"}',
        f'    attach_object_ids: {_strs(scene.grasp_target_ids())}',
        f'    object_ids: {_strs([o.id for o in objs])}',
        '    objects:',
    ]
    for o in objs:
        out.append(f'      {o.id}:')
        if o.is_mesh():
            out.append('        type: mesh')
            out.append(f'        mesh_path: "{o.mesh_resource or ""}"')
            out.append(f'        scale: {_nums(o.scale)}')
        elif o.shape is ShapeType.SPHERE:
            out.append('        type: sphere')
            out.append(f'        radius: {_num(o.dims[0])}')
        elif o.shape is ShapeType.CYLINDER:
            out.append('        type: cylinder')
            out.append(f'        radius: {_num(o.dims[0])}')
            out.append(f'        height: {_num(o.dims[1])}')
        else:  # box (cone/others fall back to their AABB box)
            out.append('        type: box')
            out.append(f'        size: {_nums(o.aabb_dims())}')
        out.append(f'        position: {_nums(o.position)}')
        out.append(f'        orientation: {_nums(o.orientation)}')
        out.append(f'        dynamic: {"true" if o.is_dynamic() else "false"}')
        # metadata for the future touchable-ACM refinement (scene_manager_node may
        # leave these attached<->static pairs allowed even when the check is ON).
        if o.touchable_collision_ids:
            out.append(f'        touchable_collision_ids: {_strs(o.touchable_collision_ids)}')
    return '\n'.join(out) + '\n'
