# =============================================================================
# TrainIt — GENERALIZED Isaac manipulation adapter (OmniGraph SCRIPT NODE).
#
# This is the REFERENCE template for the grasp physics of dynamic objects in a
# cell. It is SIMULATION-SPECIFIC: it lives hand-authored in the cell's *_isaac
# package (NOT generated by the Setup Assistant), because Isaac-internal physics
# can't be synthesized generically. The assistant owns only the ROS *contract*
# (the two topics below) + the config; THIS file realises the physics.
#
# Copy it into your <cell>_isaac/scripts/, adjust the CONFIG block, paste it into
# an OmniGraph Script Node, and TEST it in Step 1 (grasp every object, check the
# release behaviour) before configuring the application.
#
# ── The ROS contract (wire these in the Action Graph) ───────────────────────
#   ROS2 Subscribe (Bool)  /isaac_gripper_cmd     -> Script Node input  'cmd'
#       True  = gripper CLOSE (grasp);  False = OPEN (release).
#       Published by <cell>_isaac/scripts/isaac_surface_gripper_bridge.py (the
#       GripperCommand mirror), driven by the BT's CloseGripper/OpenGripper.
#   ROS2 Subscribe (Bool)  /isaac_release_policy   -> Script Node input  'freeze'
#       True  = FREEZE released objects in place (a PLC clamp is imagined to hold
#               them); False = let them fall under GRAVITY.
#       Published by the BT's SetReleasePolicy node. If you don't wire it, 'freeze'
#       stays at its default (FREEZE) and the cycle still runs.
#
# ── Grasp method ────────────────────────────────────────────────────────────
#   FIXED_JOINT (default): one rigid UsdPhysics.FixedJoint EE<->object per object,
#     at the current relative pose. Rigid -> no oscillation (the method that
#     stabilised the 20 bottles). Renders because it is physics-driven.
#   SURFACE_GRIPPER: use an IsaacSurfaceGripper instead (compliant suction). Set
#     GRASP_METHOD = "surface_gripper" and provide setup_surface_gripper.py; the
#     central objects may oscillate — prefer FIXED_JOINT unless you need suction.
# =============================================================================

# ── CONFIG (edit for your cell) ──────────────────────────────────────────────
ROBOT_PATH    = "/World/fr30_eef"      # articulation root prim of the robot
EE_LINK_NAME  = "end_effector"         # link the objects attach to (body0)
OBJECT_PREFIX = "bottle_"              # dynamic objects to grasp: prims /World/<prefix>*
DEFAULT_FREEZE = True                  # release policy if /isaac_release_policy is unwired
GRASP_METHOD  = "fixed_joint"          # "fixed_joint" | "surface_gripper"
# ─────────────────────────────────────────────────────────────────────────────


def _log(msg):
    try:
        import carb
        carb.log_warn(msg)
    except Exception:
        print(msg)


def _ensure_state(st):
    if getattr(st, "version", None) != "adapter_v1":
        st.version = "adapter_v1"
        st.gripped = False
        st.joints = []
        st.ee = None
        st.alive = False
        st.last_cmd = None


def setup(db):
    _ensure_state(db.per_instance_state)


def _l2w(stage, path):
    from pxr import Usd, UsdGeom
    return UsdGeom.Xformable(stage.GetPrimAtPath(path)).ComputeLocalToWorldTransform(
        Usd.TimeCode.Default())


def _objects(stage):
    return [p.GetPath().pathString for p in stage.Traverse()
            if p.GetName().startswith(OBJECT_PREFIX) and p.GetParent().GetName() == "World"]


def _set_kinematic(stage, path, kin):
    from pxr import UsdPhysics
    prim = stage.GetPrimAtPath(path)
    if prim and prim.IsValid():
        UsdPhysics.RigidBodyAPI.Apply(prim).CreateKinematicEnabledAttr(kin)


def _set_gravity(stage, path, gravity_on):
    from pxr import PhysxSchema
    prim = stage.GetPrimAtPath(path)
    if prim and prim.IsValid():
        PhysxSchema.PhysxRigidBodyAPI.Apply(prim).CreateDisableGravityAttr(not gravity_on)


def _make_fixed_joint(stage, ee_path, obj_path, jp):
    from pxr import UsdPhysics, Gf, Sdf
    ee_l2w = _l2w(stage, ee_path)
    b_l2w = _l2w(stage, obj_path)
    rel = b_l2w * ee_l2w.GetInverse()          # object in the EE frame (current pose)
    t = rel.ExtractTranslation(); q = rel.ExtractRotationQuat(); im = q.GetImaginary()
    j = UsdPhysics.FixedJoint.Define(stage, Sdf.Path(jp))
    j.CreateBody0Rel().SetTargets([Sdf.Path(ee_path)])
    j.CreateBody1Rel().SetTargets([Sdf.Path(obj_path)])
    j.CreateLocalPos0Attr().Set(Gf.Vec3f(float(t[0]), float(t[1]), float(t[2])))
    j.CreateLocalRot0Attr().Set(Gf.Quatf(float(q.GetReal()),
                                         float(im[0]), float(im[1]), float(im[2])))
    j.CreateLocalPos1Attr().Set(Gf.Vec3f(0.0, 0.0, 0.0))
    j.CreateLocalRot1Attr().Set(Gf.Quatf(1.0, 0.0, 0.0, 0.0))


def compute(db):
    import omni.usd
    from pxr import Sdf
    stage = omni.usd.get_context().get_stage()
    if stage is None:
        return True
    st = db.per_instance_state
    _ensure_state(st)

    if not st.alive:
        _log(f"[adapter] Isaac manipulation adapter ACTIVE (method={GRASP_METHOD})")
        st.alive = True

    try:
        cmd = bool(db.inputs.cmd)
    except Exception as e:
        _log(f"[adapter] ERROR: input 'cmd' missing ({e}) — wire /isaac_gripper_cmd")
        return True
    try:
        freeze = bool(db.inputs.freeze)
    except Exception:
        freeze = DEFAULT_FREEZE                 # /isaac_release_policy unwired -> default

    if cmd == st.last_cmd:                       # edge-triggered
        return True
    st.last_cmd = cmd

    if st.ee is None:
        for p in stage.Traverse():
            if p.GetName() == EE_LINK_NAME and p.GetPath().pathString.startswith(ROBOT_PATH):
                st.ee = p.GetPath().pathString
                break
        if st.ee is None:
            _log(f"[adapter] ERROR: link '{EE_LINK_NAME}' not found under {ROBOT_PATH}")
            return True

    if cmd and not st.gripped:                   # ---- CLOSE: grasp ----
        st.gripped = True
        for jp in st.joints:
            stage.RemovePrim(Sdf.Path(jp))
        st.joints = []
        n = 0
        for b in _objects(stage):
            _set_kinematic(stage, b, False)      # dynamic (for the joint) + gravity off
            _set_gravity(stage, b, False)
            jp = f"{st.ee}/GripJoint_{b.rsplit('/', 1)[-1]}"
            try:
                _make_fixed_joint(stage, st.ee, b, jp)
                st.joints.append(jp); n += 1
            except Exception as e:
                _log(f"[adapter] joint {b} failed: {e}")
        _log(f"[adapter] CLOSE -> {n} fixed joints EE<->object (rigid follow)")

    if not cmd and st.gripped:                   # ---- OPEN: release (freeze|gravity) ----
        st.gripped = False
        for jp in st.joints:
            stage.RemovePrim(Sdf.Path(jp))
        st.joints = []
        if freeze:
            for b in _objects(stage):
                _set_kinematic(stage, b, True)
            _log("[adapter] OPEN -> FREEZE (kinematic, immobile)")
        else:
            for b in _objects(stage):
                _set_kinematic(stage, b, False)
                _set_gravity(stage, b, True)
            _log("[adapter] OPEN -> GRAVITY (dynamic, fall)")
    return True


def cleanup(db):
    st = db.per_instance_state
    st.gripped = False
