"""pick_and_place application template — the MVP.

Emits a uniform ``MoveWaypoint`` sequence (order from ``application.sequence``, or
derived from waypoint roles) interleaved with scene setup and tool actions
(Close/OpenGripper, Attach/DetachObject) anchored at their waypoints — exactly the
shape of the golden ``pick_place.xml``.
"""

from __future__ import annotations

from typing import List

from ..model import CanonicalProject
from ..model.enums import AppType, ToolActionKind
from .base import (
    ApplicationTemplate,
    payload_dims_key,
    scene_dims_key,
    scene_pos_key,
)

# Canonical pick_and_place order when no explicit sequence is given.
_DEFAULT_ROLE_ORDER = [
    'home', 'pre_pick', 'pick', 'post_pick',
    'pre_place', 'place', 'post_place', 'home',
]


def _camel(text: str) -> str:
    return ''.join(part.capitalize() for part in text.replace('-', '_').split('_') if part)


def _fmt_num(value) -> str:
    if isinstance(value, bool):
        return 'true' if value else 'false'
    f = float(value)
    return str(int(f)) if f == int(f) else repr(f)


def _semicolon(values) -> str:
    return ';'.join(_fmt_num(v) for v in values)


class PickAndPlace(ApplicationTemplate):
    app_type = AppType.PICK_AND_PLACE.value

    def validate(self, project: CanonicalProject) -> List[str]:
        app = project.application
        problems: List[str] = []
        names = {wp.name for wp in app.waypoints}
        seq = app.sequence or self._derived_sequence(project)
        if not seq:
            problems.append('pick_and_place: no waypoint sequence')
        for wp_name in seq:
            if wp_name not in names:
                problems.append(f'sequence references unknown waypoint "{wp_name}"')
        # a grasp + release should exist for a real pick&place
        kinds = {a.kind for a in app.tool_actions}
        if ToolActionKind.GRASP not in kinds:
            problems.append('pick_and_place: no grasp tool action')
        if ToolActionKind.RELEASE not in kinds:
            problems.append('pick_and_place: no release tool action')
        # attach/detach must reference a known payload
        for action in app.tool_actions:
            if action.kind in (ToolActionKind.ATTACH, ToolActionKind.DETACH):
                pid = action.payload_ref
                if not project.scene.payload or project.scene.payload.id != pid:
                    problems.append(
                        f'{action.kind.value} references unknown payload "{pid}"')
        return problems

    def tree_filename(self, project: CanonicalProject) -> str:
        return 'pick_place.xml'

    def build_tree_xml(self, project: CanonicalProject) -> str:
        app = project.application
        seq = app.sequence or self._derived_sequence(project)
        seq_name = _camel(project.robot.robot_name) + 'PickPlace'
        label = f'{project.robot.robot_name} pick-and-place (BT, data-driven)'

        out: List[str] = []
        out.append('<?xml version="1.0" encoding="UTF-8"?>')
        out.append('<!-- Generated by the TrainIt Setup Assistant (pick_and_place). '
                   'Uniform MoveWaypoint sequence; every DOF is in config/bt_params.yaml. -->')
        out.append(f'<root BTCPP_format="4" main_tree_to_execute="{app.bt_tree_id}">')
        out.append(f'  <BehaviorTree ID="{app.bt_tree_id}">')
        out.append(f'    <Sequence name="{seq_name}">')
        out.append(f'      <Log message="{label}: start"/>')
        out.append('')

        # When a scene loader is used (Step 2 base config -> scene_manager_node loads
        # config/scene.yaml at startup), the obstacles are already in the planning
        # scene — the tree must NOT re-add them. Otherwise (from-scratch path) add the
        # static/actuated collision objects in the tree as before.
        uses_scene_loader = bool(project.robot.base_moveit_config_path)
        if not uses_scene_loader:
            for obj in project.scene.objects:
                if obj.is_planning_collision():
                    out.append(
                        f'      <AddCollisionObject id="{obj.id}" frame="{obj.frame}" '
                        f'dims="{{{scene_dims_key(obj.id)}}}" '
                        f'position="{{{scene_pos_key(obj.id)}}}"/>'
                    )
            out.append('')

        # Process-layer loop (the Loop block): repeat the move body via the BT.CPP
        # built-in Repeat decorator. -1 = forever, N>0 = N cycles, 0 = no loop.
        loop = app.loop_cycles
        body_indent = '      '
        if loop != 0:
            out.append(f'      <Repeat num_cycles="{loop}">')
            out.append(f'        <Sequence name="{seq_name}Cycle">')
            body_indent = '          '

        for wp_name in seq:
            # per-move planning-collision check for held objects (SetBool service): ON
            # before a transfer that must route the payload around the static meshes.
            seg = app.segment_for(wp_name)
            if seg is not None and seg.attached_collision_check is not None:
                val = 'true' if seg.attached_collision_check else 'false'
                out.append(f'{body_indent}<SetAttachedCollisionCheck value="{val}"/>')
            out.append(f'{body_indent}<MoveWaypoint waypoint="{wp_name}"/>')
            acts = app.actions_at(wp_name)
            for action in acts:
                if action.kind is not ToolActionKind.RESET_SCENE:
                    out.append(body_indent + self._render_action(action, project))
            # process-layer pause (the Wait block): BT.CPP built-in Sleep.
            if seg is not None and seg.wait_after_ms > 0:
                out.append(f'{body_indent}<Sleep msec="{seg.wait_after_ms}"/>')
            # scene reset LAST (after the pause): the cycle boundary of a looping app.
            for action in acts:
                if action.kind is ToolActionKind.RESET_SCENE:
                    out.append(body_indent + self._render_action(action, project))

        if loop != 0:
            out.append('        </Sequence>')
            out.append('      </Repeat>')

        out.append('')
        out.append(f'      <Log message="{label}: complete"/>')
        out.append('    </Sequence>')
        out.append('  </BehaviorTree>')
        out.append('</root>')
        return '\n'.join(out) + '\n'

    # --- helpers ---
    def _derived_sequence(self, project: CanonicalProject) -> List[str]:
        names = {wp.name for wp in project.application.waypoints}
        return [n for n in _DEFAULT_ROLE_ORDER if n in names]

    def _render_action(self, action, project: CanonicalProject) -> str:
        payload = project.scene.payload
        link = payload.attach_link if payload else 'tcp'
        if action.kind is ToolActionKind.GRASP:
            return '<CloseGripper/>'
        if action.kind is ToolActionKind.RESET_SCENE:
            return '<ResetScene/>'
        if action.kind is ToolActionKind.RELEASE:
            # with a scene loader (Isaac flow), tell the manipulation adapter what the
            # released object does (freeze|gravity) BEFORE opening the grip. Without one
            # (from-scratch path) a plain OpenGripper — no Isaac adapter to signal.
            if project.robot.base_moveit_config_path:
                policy = project.scene.release_policy().value
                return (f'<SetReleasePolicy policy="{policy}"/>\n'
                        f'      <OpenGripper/>')
            return '<OpenGripper/>'
        if action.kind is ToolActionKind.ATTACH:
            offset = _semicolon(payload.attach_offset) if payload else '0;0;0'
            return (f'<AttachObject id="{action.payload_ref}" link="{link}" '
                    f'dims="{{{payload_dims_key(action.payload_ref)}}}" '
                    f'position="{offset}"/>')
        if action.kind is ToolActionKind.DETACH:
            return f'<DetachObject id="{action.payload_ref}" link="{link}"/>'
        return f'<!-- unknown tool action {action.kind} -->'
