"""Canonical project data model (the single source of truth)."""

from .backend import BackendProfile, profile_for
from .enums import (
    AppType,
    Backend,
    CalibrationFrame,
    EndEffectorActuation,
    GripperJointTarget,
    SimGraspAdapter,
    DetectionMethod,
    EndEffector,
    GripperKind,
    IsaacGraspMethod,
    MotionType,
    PlannerId,
    PolicyCategory,
    PolicyMode,
    ReleasePolicy,
    SceneObjectCategory,
    SceneObjectSource,
    ShapeType,
    ToolActionKind,
    WaypointRole,
    WaypointType,
)
from .deployment import DeploymentSpec, LaunchNodeSpec, RealIncludeSpec
from .io import load_project, project_to_dict, save_project
from .perception import (CameraSpec, DetectorSpec, PerceptionSpec,
                         RelativeBinding, VisionBinding)
from .project import BundleSpec, CanonicalProject, ProjectMeta, SCHEMA_VERSION
from .robot import (
    ArmControllerSpec,
    DescriptionSource,
    DisableCollisionSpec,
    GripperSpec,
    JointLimit,
    JointLimitsSpec,
    KinematicsSpec,
    NamedState,
    OmplGroupSpec,
    PilzCartesianLimits,
    PlanningGroupSpec,
    RobotSpec,
)
from .scene import Payload, SceneObject, SceneSpec
from .task import (ApplicationSpec, DetectPoint, MotionSegment, PolicyStep,
                   ToolAction, Waypoint)

__all__ = [
    'SCHEMA_VERSION',
    'CanonicalProject',
    'BundleSpec',
    'ProjectMeta',
    'RobotSpec',
    'DescriptionSource',
    'PlanningGroupSpec',
    'NamedState',
    'DisableCollisionSpec',
    'KinematicsSpec',
    'JointLimit',
    'JointLimitsSpec',
    'OmplGroupSpec',
    'PilzCartesianLimits',
    'GripperSpec',
    'ArmControllerSpec',
    'SceneSpec',
    'SceneObject',
    'Payload',
    'ApplicationSpec',
    'Waypoint',
    'MotionSegment',
    'ToolAction',
    'PolicyStep',
    'DeploymentSpec',
    'LaunchNodeSpec',
    'RealIncludeSpec',
    # perception (TSA v4, D-015)
    'PerceptionSpec',
    'CameraSpec',
    'DetectorSpec',
    'VisionBinding',
    'RelativeBinding',
    'DetectPoint',
    'DetectionMethod',
    # enums
    'WaypointType',
    'MotionType',
    'PlannerId',
    'GripperKind',
    'AppType',
    'SceneObjectSource',
    'SceneObjectCategory',
    'ShapeType',
    'ReleasePolicy',
    'IsaacGraspMethod',
    'WaypointRole',
    'ToolActionKind',
    'PolicyMode',
    'PolicyCategory',
    'EndEffector',
    'CalibrationFrame',
    # backend (ADR-0008)
    'Backend',
    'BackendProfile',
    'profile_for',
    # end-effector abstraction (ADR-0010)
    'EndEffectorActuation',
    'GripperJointTarget',
    'SimGraspAdapter',
    # io
    'load_project',
    'save_project',
    'project_to_dict',
]
