#!/usr/bin/env python3
# -----------------------------------------------------------------------------
# cell bring-up for the TrainIt Motion Runtime (mock | isaac | real).
# Generated by the TrainIt Setup Assistant.
#
# move_group is configured by build_move_group_params(): robot-specific data from
# cell_trainit_config + the GENERIC planner pipelines (ompl/pilz/chomp)
# from the trainit_motion_runtime framework.
#
#   ros2 launch cell_app bringup.launch.py mode:=isaac
# -----------------------------------------------------------------------------
import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import (DeclareLaunchArgument, IncludeLaunchDescription,
                            LogInfo, OpaqueFunction, RegisterEventHandler)
from launch.event_handlers import OnProcessExit
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node

from trainit_motion_runtime.trainit_moveit_config import build_move_group_params

MOVEIT_CONFIG_PACKAGE = "cell_trainit_config"
ROBOT_NAME = "cell"
ARM_CONTROLLER = "moveit_joint_controller"
VALID_MODES = ('mock', 'isaac', 'real')
ARM_JS_REMAP_TO = None
BRIDGES = []
REAL_INCLUDE = None
GRIPPER_MOCK_ACTION = None


def launch_setup(context, *args, **kwargs):
    mode = LaunchConfiguration("mode").perform(context)
    use_rviz = LaunchConfiguration("rviz").perform(context).lower() in ("true", "1")
    if mode not in VALID_MODES:
        raise RuntimeError(f"Unknown mode '{mode}'. Valid: {', '.join(VALID_MODES)}")

    use_isaac = (mode == "isaac")
    use_sim_time = use_isaac
    common = {"use_sim_time": use_sim_time}

    params, mc = build_move_group_params(
        robot_name=ROBOT_NAME, moveit_config_package=MOVEIT_CONFIG_PACKAGE, use_isaac=use_isaac)

    moveit_share = get_package_share_directory(MOVEIT_CONFIG_PACKAGE)
    ros2_controllers_path = os.path.join(moveit_share, "config", "ros2_controllers.yaml")
    rviz_config_path = os.path.join(moveit_share, "config", "moveit.rviz")

    nodes = [
        LogInfo(msg=f"[{ROBOT_NAME} bringup] mode={mode} use_sim_time={use_sim_time}"),
        Node(package="robot_state_publisher", executable="robot_state_publisher",
             output="screen", parameters=[mc.robot_description, common]),
        Node(package="moveit_ros_move_group", executable="move_group",
             output="screen", parameters=[params, common]),
    ]

    if mode in ("mock", "isaac"):
        rc_remap = [("/joint_states", ARM_JS_REMAP_TO)] if ARM_JS_REMAP_TO else []
        nodes.append(Node(
            package="controller_manager", executable="ros2_control_node",
            output="screen",
            parameters=[mc.robot_description, ros2_controllers_path, common],
            remappings=rc_remap))

        controllers = ["joint_state_broadcaster", ARM_CONTROLLER]
        spawners = [
            Node(package="controller_manager", executable="spawner",
                 arguments=[c, "--controller-manager", "/controller_manager",
                            "--controller-manager-timeout", "60"],
                 output="screen")
            for c in controllers
        ]
        nodes.append(spawners[0])
        for prev, nxt in zip(spawners, spawners[1:]):
            nodes.append(RegisterEventHandler(OnProcessExit(target_action=prev, on_exit=[nxt])))

        # mock gripper action server: only in mock, and only when no cell bridge serves
        # the gripper (empty BRIDGES = a fresh bootstrap). Lets CloseGripper succeed.
        if mode == "mock" and GRIPPER_MOCK_ACTION and not BRIDGES:
            nodes.append(Node(
                package="cell_app", executable="mock_gripper_action_server.py",
                output="screen", parameters=[{"action": GRIPPER_MOCK_ACTION}, common]))

        for b in BRIDGES:
            if mode in b.get("modes", ["mock", "isaac"]):
                node_kwargs = {}
                if b.get("name"):
                    node_kwargs["name"] = b["name"]
                nodes.append(Node(
                    package=b["package"], executable=b["executable"], output="screen",
                    parameters=[dict(p) for p in b.get("parameters", [])] + [common],
                    remappings=[tuple(r) for r in b.get("remappings", [])],
                    **node_kwargs))
    else:  # real
        if REAL_INCLUDE:
            nodes.append(LogInfo(msg=f"[{ROBOT_NAME} bringup] mode=real: launching hardware bridge"))
            nodes.append(IncludeLaunchDescription(
                PythonLaunchDescriptionSource(os.path.join(
                    get_package_share_directory(REAL_INCLUDE["package"]),
                    "launch", REAL_INCLUDE["launch_file"]))))

    if use_rviz:
        # RViz's MotionPlanning display runs its OWN PlanningSceneMonitor. If it inherits
        # move_group's publish_planning_scene flags it starts PUBLISHING on
        # monitored_planning_scene (the very topic it also subscribes to) -> a self-sustaining
        # echo of stale FULL scenes that resurrects removed/attached objects (grasped bottles
        # reappear ~1s after grasp). Give RViz a params copy with those flags OFF so only
        # move_group publishes; RViz just subscribes.
        rviz_params = dict(params)
        for _k in ("publish_planning_scene", "publish_geometry_updates",
                   "publish_state_updates", "publish_transforms_updates"):
            rviz_params[_k] = False
        nodes.append(Node(
            package="rviz2", executable="rviz2", output="log",
            arguments=["-d", rviz_config_path],
            parameters=[rviz_params, common]))

    return nodes


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument("mode", default_value="isaac",
                              description="Backend: mock | isaac | real"),
        DeclareLaunchArgument("rviz", default_value="true",
                              description="Launch RViz with the MoveIt plugin"),
        OpaqueFunction(function=launch_setup),
    ])
